/**
 * DRAFT: Capsule 01 — Dirt Road Heirlooms / Vol. 01
 *
 * 11 product entries to be merged into MOCK_PRODUCTS in src/lib/mock-data.ts.
 * Generated by the Capsule 01 parallel spec phase. DO NOT IMPORT FROM THIS FILE
 * IN PRODUCTION — it exists only as a hand-off to the merger.
 *
 * --------------------------------------------------------------------------
 * DECISIONS MADE (re-check anything flagged with REVIEW):
 * --------------------------------------------------------------------------
 *
 * 1. SLUG PATTERN
 *    `capsule-01-NN-shortname` (zero-padded for 1–9; 0a / 0b for add-ons).
 *    Keeps the capsule grouped and alphabetically sortable on /shop.
 *
 *      capsule-01-0a-bullion-cap
 *      capsule-01-0b-pin-set
 *      capsule-01-01-member-001
 *      capsule-01-02-patron-saint
 *      capsule-01-03-last-light
 *      capsule-01-04-order-of-the-hoodlum   (flagship)
 *      capsule-01-05-hoodlums-only
 *      capsule-01-06-quiet-hoodlum
 *      capsule-01-07-chapter-01
 *      capsule-01-08-club-issue-24
 *      capsule-01-09-homecoming-24
 *
 * 2. ID NAMESPACE
 *    `cap01_0a`, `cap01_0b`, `cap01_01` … `cap01_09` — guaranteed not to
 *    collide with the existing `prod_XXX` IDs.
 *
 * 3. CATEGORY MAPPING
 *    - Tees:       pieces 1, 2, 3
 *    - Hoodies:    pieces 4, 5, 6, 8
 *    - Hoodies:    pieces 7, 9  (crewnecks live under "hoodies" per the
 *                  existing prod_016 Vintage Crewneck convention)
 *    - Hats:       piece 0a
 *    - Accessories: piece 0b
 *
 * 4. IMAGE PATHS
 *    Existing local files used where present:
 *      Piece 1 → /images/products/capsule-01/piece-01-member-001.jpg     OK
 *      Piece 2 → /images/products/capsule-01/piece-02-patron-saint.jpg   OK
 *      Piece 4 → /images/products/capsule-01/piece-04-order-flagship.jpg OK
 *                 (already exists — task brief listed it as missing but
 *                  the JPG mockup is on disk; using it. REVIEW.)
 *      Piece 5 → /images/products/capsule-01/piece-05-hoodlums-only.jpg  OK
 *      Piece 6 → /images/products/capsule-01/piece-06-quiet-hoodlum.jpg  OK
 *      Piece 7 → /images/products/capsule-01/piece-07-chapter-01.jpg     OK
 *      Piece 9 → /images/products/capsule-01/piece-09-homecoming-24.jpg  OK
 *
 *    Placeholders for files not yet generated (image-gen pipeline will
 *    drop matching filenames into the capsule-01 directory):
 *      Piece 0a → /images/products/capsule-01/piece-0a-bullion-cap.jpg
 *      Piece 0b → /images/products/capsule-01/piece-0b-pinset-membercard.jpg
 *      Piece 3  → /images/products/capsule-01/piece-03-last-light.jpg
 *                  (replacing /artwork/capsule-01/piece-03-back.png raw artwork)
 *      Piece 8  → /images/products/capsule-01/piece-08-club-issue.jpg
 *                  (replacing /artwork/capsule-01/piece-08-front.png raw artwork)
 *
 *    `image` and `cartoonImage` are set to the SAME path for every capsule
 *    entry — capsule pieces don't have separate cartoon variants.
 *
 * 5. SIZES
 *    Pulled from PRINTFUL_VARIANT_MAP in capsule-01-data.ts:
 *      pieces 1, 2, 4, 5, 6, 7  → S, M, L, XL, 2XL, 3XL
 *      pieces 3, 8, 9           → S, M, L, XL, 2XL          (no 3XL)
 *      pieces 0a, 0b            → ["One Size"]
 *
 * 6. PRINTFUL FIELDS
 *    Populated for the 9 numbered pieces (all map to a Printful blank in
 *    PRINTFUL_VARIANT_MAP) — even those whose `fulfillmentPath` is
 *    "off-platform" still have a Printful blank ID on the source data;
 *    the off-platform routing is a fulfillment-layer decision, not a
 *    product-record decision, so the IDs/variants are preserved here for
 *    downstream sync flexibility. REVIEW if the merger wants off-platform
 *    pieces to *omit* Printful fields entirely.
 *
 *    Pieces 0a (cap) and 0b (pin set) are fully off-platform — Printful
 *    fields are omitted.
 *
 *    `printfulColor` values come from PRINTFUL_VARIANT_MAP, which uses
 *    the *colorway label that exists on the Printful catalog* (e.g. piece 1
 *    Printful ID 586 is "Pepper" in the map, not the doc's "Pepper" prose
 *    — same thing, just confirming). Piece 3's blank (Shaka SHHTDS, ID 515)
 *    has a single tie-dye variant labeled "Black / White" in the map; this
 *    is the actual Printful color slug, not pretty marketing copy.
 *
 * 7. isNew / isSoldOut
 *    All 11 pieces: `isNew: true`, `isSoldOut: false`.
 *    "Coming Soon" gating is handled at the shop UI layer (separate concern).
 *
 * 8. PRICE
 *    Pulled directly from the `retail` field in CAPSULE_01_PIECES — these
 *    are the canonical revised numbers (post-pricing-agent), which differ
 *    from the original markdown prompt. Trust the data file.
 *
 * 9. DESCRIPTION
 *    Punchy 1–2 sentence summaries built from each piece's `designSummary`
 *    and `lever`, with edition counts where they're load-bearing. Kept
 *    terse and on-brand — no "premium quality" filler.
 *
 * --------------------------------------------------------------------------
 */

import type { Product } from "./mock-data";

export const CAPSULE_01_PRODUCT_DRAFTS: Product[] = [
  // ---------- PIECE 0a: Bullion CH Cap (off-platform) ----------
  {
    id: "cap01_0a",
    name: "Bullion CH Cap",
    slug: "capsule-01-0a-bullion-cap",
    price: 68,
    category: "hats",
    isNew: true,
    isSoldOut: false,
    description:
      "Custom 6-panel in Bonfire Black with the same bullion-stitch skull-cowboy from Piece 6 shrunk to a hat-front crest. Hand-stamped edition number on the inside sweatband — the entry-point that signals everything else without saying anything. Capped at 300.",
    sizes: ["One Size"],
    image: "/images/products/capsule-01/piece-0a-bullion-cap.jpg",
    cartoonImage: "/images/products/capsule-01/piece-0a-bullion-cap.jpg",
  },

  // ---------- PIECE 0b: Pin Set + Member Card (off-platform) ----------
  {
    id: "cap01_0b",
    name: "Pin Set + Member Card",
    slug: "capsule-01-0b-pin-set",
    price: 24,
    category: "accessories",
    isNew: true,
    isSoldOut: false,
    description:
      "Three hard-enamel pins — CH monogram, skull-cowboy mascot, EST 2024 oval — backed on a kraft member card with a hand-stamped number. Sub-$50 entry to the Charter Roll. $24 says you were here. Capped at 1,000.",
    sizes: ["One Size"],
    image: "/images/products/capsule-01/piece-0b-pinset-membercard.jpg",
    cartoonImage: "/images/products/capsule-01/piece-0b-pinset-membercard.jpg",
  },

  // ---------- PIECE 1: Member Number 001 Tee (Comfort Colors 1717 · Pepper) ----------
  {
    id: "cap01_01",
    name: "Member Number 001 Tee",
    slug: "capsule-01-01-member-001",
    price: 78,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Comfort Colors 1717 in Pepper (washed near-black). Tiny gold hem stamp up front; full typographic charter crest across the back — type only, no illustrations. Every member gets a number. Yours is 001. So is everyone else's. Capped at 700.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/capsule-01/piece-01-member-001.jpg",
    cartoonImage: "/images/products/capsule-01/piece-01-member-001.jpg",
    printfulProductId: 586,
    printfulColor: "Pepper",
    printfulVariantIds: {
      S: 17693,
      M: 17694,
      L: 17695,
      XL: 17696,
      "2XL": 17697,
      "3XL": 17698,
    },
  },

  // ---------- PIECE 2: Patron Saint of Bad Decisions Tee (AS Colour 5082 · Faded Bone) ----------
  {
    id: "cap01_02",
    name: "Patron Saint of Bad Decisions Tee",
    slug: "capsule-01-02-patron-saint",
    price: 88,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "AS Colour 5082 oversized in Faded Bone. Religious santo-card portrait of the skull-cowboy reframed as a saint — full antique-gold halo with rays terminating in tiny scene-objects. Owning one inducts you into the church of bad decisions. Hand-numbered to 100.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/capsule-01/piece-02-patron-saint.jpg",
    cartoonImage: "/images/products/capsule-01/piece-02-patron-saint.jpg",
    printfulProductId: 713,
    printfulColor: "Faded Bone",
    printfulVariantIds: {
      S: 17570,
      M: 17575,
      L: 17580,
      XL: 17585,
      "2XL": 17590,
      "3XL": 17595,
    },
  },

  // ---------- PIECE 3: Last Light, County Line Tee (Shaka SHHTDS · Tie-dye) ----------
  {
    id: "cap01_03",
    name: "Last Light, County Line Tee",
    slug: "capsule-01-03-last-light",
    price: 84,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Shaka SHHTDS in Black/Creek Cream tie-dye — discharge directly into the dye so the chaos becomes the sky. Tiny edition stamp up front; massive cinematic back panel of a lifted truck on a ridge, bonfire, oak tree, two figures on the tailgate. Capped at 250.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    image: "/images/products/capsule-01/piece-03-last-light.jpg",
    cartoonImage: "/images/products/capsule-01/piece-03-last-light.jpg",
    printfulProductId: 515,
    printfulColor: "Black / White",
    printfulVariantIds: {
      S: 12956,
      M: 12957,
      L: 12959,
      XL: 12960,
      "2XL": 12961,
    },
  },

  // ---------- PIECE 4: Order of the Hoodlum Hoodie (Independent PRM4500 · Pigment Black) — FLAGSHIP ----------
  {
    id: "cap01_04",
    name: "Order of the Hoodlum Hoodie",
    slug: "capsule-01-04-order-of-the-hoodlum",
    price: 248,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "FLAGSHIP. Independent PRM4500 in Pigment Black. Two-color tonal embroidered medallion on the chest; heraldic shield back with rope border, crossed longneck + horseshoe X, skull-cowboy face, and a hand-numbered NO. ___ OF 200. Only 200 get inducted.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/capsule-01/piece-04-order-flagship.jpg",
    cartoonImage: "/images/products/capsule-01/piece-04-order-flagship.jpg",
    printfulProductId: 542,
    printfulColor: "Pigment Black",
    printfulVariantIds: {
      S: 13663,
      M: 13664,
      L: 13665,
      XL: 13666,
      "2XL": 13667,
      "3XL": 13668,
    },
  },

  // ---------- PIECE 5: HOODLUMS ONLY Hoodie (Comfort Colors 1567 · Pepper) ----------
  {
    id: "cap01_05",
    name: "HOODLUMS ONLY Hoodie",
    slug: "capsule-01-05-hoodlums-only",
    price: 148,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Comfort Colors 1567 in Pepper. Hood-down, only a small members-club chest crest signals affiliation. Hood-up, HOODLUMS / ONLY broadcasts in 4-inch gold blackletter across the crown. Wearer controls the volume. Capped at 600.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/capsule-01/piece-05-hoodlums-only.jpg",
    cartoonImage: "/images/products/capsule-01/piece-05-hoodlums-only.jpg",
    printfulProductId: 970,
    printfulColor: "Pepper",
    printfulVariantIds: {
      S: 24850,
      M: 24851,
      L: 24852,
      XL: 24853,
      "2XL": 24854,
      "3XL": 24855,
    },
  },

  // ---------- PIECE 6: The Quiet Hoodlum Hoodie (Lane Seven LS16001GD · Pigment Burro) ----------
  {
    id: "cap01_06",
    name: "The Quiet Hoodlum Hoodie",
    slug: "capsule-01-06-quiet-hoodlum",
    price: 168,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Lane Seven LS16001GD in Pigment Burro. Tiny bullion-stitch skull-cowboy at center chest — bandana up, only two gold grillz peek. Micro tonal hem stamp HOODLUMS · MMXXIV · 1 OF 200. Clean back. Restraint is the flex. Capped at 200.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/capsule-01/piece-06-quiet-hoodlum.jpg",
    cartoonImage: "/images/products/capsule-01/piece-06-quiet-hoodlum.jpg",
    printfulProductId: 975,
    printfulColor: "Pigment Burro",
    printfulVariantIds: {
      S: 34360,
      M: 34363,
      L: 34366,
      XL: 34369,
      "2XL": 34372,
      "3XL": 34375,
    },
  },

  // ---------- PIECE 7: Chapter 01 Pocket Crest Crewneck (Comfort Colors 1566 · Pepper) ----------
  {
    id: "cap01_07",
    name: "Chapter 01 Pocket Crest Crewneck",
    slug: "capsule-01-07-chapter-01",
    price: 118,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Comfort Colors 1566 in Pepper. Vertical shield crest pulled to the right chest — vintage workwear breast-pocket position. Gold CH monogram with a hidden 01 in the H's negative space. Hand-numbered nape strip. One of five hundred. Center is for everybody else.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/capsule-01/piece-07-chapter-01.jpg",
    cartoonImage: "/images/products/capsule-01/piece-07-chapter-01.jpg",
    printfulProductId: 839,
    printfulColor: "Pepper",
    printfulVariantIds: {
      S: 21980,
      M: 21981,
      L: 21982,
      XL: 21983,
      "2XL": 21984,
      "3XL": 21985,
    },
  },

  // ---------- PIECE 8: Club Issue No. 24 Hoodie (Champion GDS101 · Storm tie-dye) ----------
  {
    id: "cap01_08",
    name: "Club Issue No. 24 Hoodie",
    slug: "capsule-01-08-club-issue-24",
    price: 218,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Champion GDS101 in Storm tie-dye. A single 3.25-inch tonal embroidered medallion at the chest — threads picked one shade off the darkest dye zones so the crest appears and disappears as the fabric bunches. Loud printing on tie-dye is what dropshippers do; tonal embroidery is what clubs do. Capped at 150.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    image: "/images/products/capsule-01/piece-08-club-issue.jpg",
    cartoonImage: "/images/products/capsule-01/piece-08-club-issue.jpg",
    printfulProductId: 464,
    printfulColor: "Black",
    printfulVariantIds: {
      S: 11986,
      M: 11987,
      L: 11988,
      XL: 11989,
      "2XL": 11990,
    },
  },

  // ---------- PIECE 9: Class of '24 Homecoming Crew (Champion S149 · Bonfire Black) ----------
  {
    id: "cap01_09",
    name: "Class of '24 Homecoming Crew",
    slug: "capsule-01-09-homecoming-24",
    price: 148,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Champion S149 in Bonfire Black. Real-deal cream wool tackle-twill 24 with antique-gold chain-stitch outline and Tobacco Olive drop shadow; HOODLUMS COUNTRY CLUB arched above. Back reads ALUMNI ASSOCIATION / Bonfire Hill / EST · MMXXIV. A fabricated memory you get to inhabit. Capped at 500.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    image: "/images/products/capsule-01/piece-09-homecoming-24.jpg",
    cartoonImage: "/images/products/capsule-01/piece-09-homecoming-24.jpg",
    printfulProductId: 318,
    printfulColor: "Black",
    printfulVariantIds: {
      S: 9659,
      M: 9660,
      L: 9661,
      XL: 9662,
      "2XL": 9663,
    },
  },
];
