export interface Product {
  id: string;
  name: string;
  slug: string;
  price: number;
  category: "tees" | "hoodies" | "hats" | "accessories" | "stickers";
  isNew: boolean;
  isSoldOut: boolean;
  description: string;
  sizes: string[];
  image: string;
  cartoonImage: string;
  printfulProductId?: number;
  printfulColor?: string;
  printfulVariantIds?: Record<string, number>;
}

export const MOCK_PRODUCTS: Product[] = [
  // ---------- HOODIES ----------
  {
    id: "prod_001",
    name: "Heritage Hoodie",
    slug: "hoodie-heritage",
    price: 78,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Heavyweight black pullover (Independent IND4000). Gold HOODLUMS COUNTRY CLUB lettering with the skull-cowboy mascot — the flagship hoodie.",
    sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/printful/hoodie-heritage.jpg",
    cartoonImage: "/images/products/hoodie-heritage-cartoon.webp",
    printfulProductId: 1543,
    printfulColor: "Black",
    printfulVariantIds: {
      "2XL": 5324352159,
      "3XL": 5324352160,
      "L": 5324352161,
      "M": 5324352162,
      "S": 5324352163,
      "XL": 5324352164,
      "XS": 5324352170,
    },
  },
  {
    id: "prod_002",
    name: '"Live Each Day" Hoodie',
    slug: "hoodie-live-each-day",
    price: 82,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Garment-dyed black pullover (Comfort Colors 1467). Full-back sunset-and-dirt-road print with the mantra arched in cream and gold.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/printful/hoodie-live-each-day.jpg",
    cartoonImage: "/images/products/hoodie-live-each-day-cartoon.webp",
    printfulProductId: 969,
    printfulColor: "Black",
    printfulVariantIds: {
      "2XL": 5324426412,
      "3XL": 5324426413,
      "L": 5324426414,
      "M": 5324426415,
      "S": 5324426416,
      "XL": 5324426417,
    },
  },
  {
    id: "prod_003",
    name: "Liquid Gold Hoodie",
    slug: "hoodie-liquid-gold",
    price: 85,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Army olive pullover (Independent SS4500). Dripping liquid-gold HOODLUMS COUNTRY CLUB lettering melts down the chest. Limited drop.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    image: "/images/products/printful/hoodie-liquid-gold.jpg",
    cartoonImage: "/images/products/hoodie-camo-crossover-cartoon.webp",
    printfulProductId: 602,
    printfulColor: "Army",
    printfulVariantIds: {
      "2XL": 5324353133,
      "L": 5324353135,
      "M": 5324353136,
      "S": 5324353137,
      "XL": 5324353138,
    },
  },
  {
    id: "prod_004",
    name: "Crew Zip Hoodie",
    slug: "hoodie-crew",
    price: 88,
    category: "hoodies",
    isNew: false,
    isSoldOut: false,
    description:
      "Black full-zip hoodie (Independent SS4500Z). Biker-patch crest on the back: crossed shotgun and fishing rod, EST. 2024 arc.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    image: "/images/products/printful/hoodie-crew.jpg",
    cartoonImage: "/images/products/hoodie-crew-cartoon.webp",
    printfulProductId: 584,
    printfulColor: "Black",
    printfulVariantIds: {
      "2XL": 5324353587,
      "L": 5324353588,
      "M": 5324353589,
      "S": 5324353590,
      "XL": 5324353591,
    },
  },
  {
    id: "prod_005",
    name: "From the Dirt Hoodie",
    slug: "hoodie-from-the-dirt",
    price: 78,
    category: "hoodies",
    isNew: false,
    isSoldOut: false,
    description:
      "Alpine green pullover (Independent SS4500). Golden tree-of-life graphic — roots spell HOODLUMS, branches spell COUNTRY CLUB.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    image: "/images/products/printful/hoodie-from-the-dirt.jpg",
    cartoonImage: "/images/products/hoodie-from-the-dirt-cartoon.webp",
    printfulProductId: 602,
    printfulColor: "Alpine Green",
    printfulVariantIds: {
      "2XL": 5324401323,
      "L": 5324401373,
      "M": 5324401374,
      "S": 5324401375,
      "XL": 5324401376,
    },
  },

  // ---------- TEES ----------
  {
    id: "prod_006",
    name: "OG Logo Tee",
    slug: "tee-og-logo",
    price: 38,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Garment-dyed heavyweight black tee (Comfort Colors 1717). Stacked cream-gold HOODLUMS COUNTRY CLUB with cracked vintage print texture.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-og-logo.jpg",
    cartoonImage: "/images/products/tee-og-logo-cartoon.webp",
    printfulProductId: 586,
    printfulColor: "Black",
    printfulVariantIds: {
      "2XL": 5324342789,
      "3XL": 5324342790,
      "4XL": 5324342791,
      "L": 5324342792,
      "M": 5324342817,
      "S": 5324342818,
      "XL": 5324342819,
    },
  },
  {
    id: "prod_007",
    name: '"Country Raised, Hood Paid" Tee',
    slug: "tee-country-raised",
    price: 42,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Oversized garment-dyed Vintage White tee (Bella + Canvas 4810). Burnout-truck illustration with the dual-identity slogan in gold-outlined brown.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/printful/tee-country-raised.jpg",
    cartoonImage: "/images/products/tee-country-raised-cartoon.webp",
    printfulProductId: 880,
    printfulColor: "Vintage White",
    printfulVariantIds: {
      "2XL": 5324417420,
      "3XL": 5324417421,
      "L": 5324417422,
      "M": 5324417423,
      "S": 5324417424,
      "XL": 5324417425,
    },
  },
  {
    id: "prod_008",
    name: "Skull & Country Tee",
    slug: "tee-skull-country",
    price: 42,
    category: "tees",
    isNew: false,
    isSoldOut: false,
    description:
      "Garment-dyed black tee (Comfort Colors 1717). Tattoo-style cowboy skull with gold grillz, crossed fishing rods, and blackletter brand arc.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-skull-country.jpg",
    cartoonImage: "/images/products/tee-skull-country-cartoon.webp",
    printfulProductId: 586,
    printfulColor: "Black",
    printfulVariantIds: {
      "2XL": 5324417731,
      "3XL": 5324417732,
      "4XL": 5324417733,
      "L": 5324417734,
      "M": 5324417735,
      "S": 5324417736,
      "XL": 5324417737,
    },
  },
  {
    id: "prod_009",
    name: '"Property Of" Tee',
    slug: "tee-property-of",
    price: 38,
    category: "tees",
    isNew: false,
    isSoldOut: false,
    description:
      "Premium charcoal heather tee (Cotton Heritage MC1086). PROPERTY OF · HOODLUMS COUNTRY CLUB · ATHLETIC DEPT. varsity print with cracked vintage texture.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-property-of.jpg",
    cartoonImage: "/images/products/tee-property-of-cartoon.webp",
    printfulProductId: 508,
    printfulColor: "Charcoal Heather",
    printfulVariantIds: {
      "2XL": 5324418350,
      "3XL": 5324418351,
      "4XL": 5324418352,
      "L": 5324418353,
      "M": 5324418354,
      "S": 5324418355,
      "XL": 5324418356,
    },
  },
  {
    id: "prod_010",
    name: "Scenic Back Tee",
    slug: "tee-scenic-back",
    price: 44,
    category: "tees",
    isNew: false,
    isSoldOut: false,
    description:
      "Garment-dyed black tee (Comfort Colors 1717). Framed bonfire-at-night back print in warm gold tones. Small CH front chest hit.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-scenic-back.jpg",
    cartoonImage: "/images/products/tee-scenic-back-cartoon.webp",
    printfulProductId: 586,
    printfulColor: "Black",
    printfulVariantIds: {
      "2XL": 5324426013,
      "3XL": 5324426014,
      "4XL": 5324426015,
      "L": 5324426018,
      "M": 5324426019,
      "S": 5324426020,
      "XL": 5324426022,
    },
  },
  {
    id: "prod_011",
    name: "Bold Statement Tee",
    slug: "tee-bold-statement",
    price: 38,
    category: "tees",
    isNew: false,
    isSoldOut: false,
    description:
      "Oversized washed black tee (Bella + Canvas 4810). Massive HOODLUM impact font with gold drop-shadow, tiny country club cursive above.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/printful/tee-bold-statement.jpg",
    cartoonImage: "/images/products/tee-bold-statement-cartoon.webp",
    printfulProductId: 880,
    printfulColor: "Washed Black",
    printfulVariantIds: {
      "2XL": 5324419520,
      "3XL": 5324419521,
      "L": 5324419522,
      "M": 5324419523,
      "S": 5324419524,
      "XL": 5324419525,
    },
  },
  {
    id: "prod_027",
    name: "Anonymous Hoodlum Tee",
    slug: "tee-anonymous-hoodlum",
    price: 48,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Limited drop. Garment-dyed heavyweight black tee (Comfort Colors 1717). Hooded figure in a Guy Fawkes mask in front of a wall of matrix-green code monitors — with a tiny gold HCC monogram tucked in the corner. If you know, you know.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-anonymous-hoodlum.jpg",
    cartoonImage: "/images/products/tee-anonymous-hoodlum.webp",
    printfulProductId: 586,
    printfulColor: "Black",
  },

  // ---------- GOLF LINE (Hoodlums Country Club golf drop) ----------
  {
    id: "prod_028",
    name: "Crossed Clubs Crest Tee",
    slug: "tee-golf-crossed-clubs",
    price: 44,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Heritage country-club crest. Crossed driver and putter with a golf ball at the intersection, HOODLUMS COUNTRY CLUB arched on top, EST. 2024 below. Garment-dyed heavyweight black tee (Comfort Colors 1717).",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-golf-crossed-clubs.jpg",
    cartoonImage: "/images/products/tee-golf-crossed-clubs.webp",
    printfulProductId: 586,
    printfulColor: "Black",
  },
  {
    id: "prod_029",
    name: "Skull Caddy Tee",
    slug: "tee-golf-skull-caddy",
    price: 48,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "The HCC skull-cowboy mascot mid-swing — cowboy hat, gold grillz, three clay-red flags planted in the turf. BAD LIES · GOOD TIMES arched below. Garment-dyed heavyweight black tee (Comfort Colors 1717).",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-golf-skull-caddy.jpg",
    cartoonImage: "/images/products/tee-golf-skull-caddy.webp",
    printfulProductId: 586,
    printfulColor: "Black",
  },
  {
    id: "prod_030",
    name: '"Bad Lies, Good Times" Tee',
    slug: "tee-golf-bad-lies",
    price: 44,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Massive stacked condensed Western type — BAD LIES over GOOD TIMES in cream with a thick antique-gold metallic outline. Tiny clay-red flag in the corner. Garment-dyed heavyweight black tee (Comfort Colors 1717).",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-golf-bad-lies.jpg",
    cartoonImage: "/images/products/tee-golf-bad-lies.webp",
    printfulProductId: 586,
    printfulColor: "Black",
  },
  {
    id: "prod_031",
    name: "18th Hole Tee",
    slug: "tee-golf-18th-hole",
    price: 42,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Single clay-red flag planted on turf green, HOODLUMS COUNTRY CLUB stitched on the flag, a small bone-cream ball at the cup. EST. 2024 · 18 HOLES in gold below. Garment-dyed heavyweight black tee (Comfort Colors 1717).",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-golf-18th-hole.jpg",
    cartoonImage: "/images/products/tee-golf-18th-hole.webp",
    printfulProductId: 586,
    printfulColor: "Black",
  },
  {
    id: "prod_032",
    name: "Country Club Emblem Tee",
    slug: "tee-golf-emblem",
    price: 46,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Vintage country-club oval emblem — skull-cowboy mascot, crossed clubs, EST. 2024, all wrapped by HOODLUMS COUNTRY CLUB on the outer ring. Garment-dyed heavyweight black tee (Comfort Colors 1717).",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-golf-emblem.jpg",
    cartoonImage: "/images/products/tee-golf-emblem.webp",
    printfulProductId: 586,
    printfulColor: "Black",
  },
  {
    id: "prod_033",
    name: "HCC Country Club Polo",
    slug: "polo-hcc-mono",
    price: 58,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "The compact HCC + crossed-clubs left-chest hit. Designed for an embroidered polo — needs a Printful polo blank wired in (Hanes/Port Authority) before fulfillment. Currently shown with the print artwork.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/tee-golf-mono.webp",
    cartoonImage: "/images/products/tee-golf-mono.webp",
  },
  {
    id: "prod_034",
    name: "Vintage Scorecard Tee",
    slug: "tee-golf-scorecard",
    price: 44,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Parchment-cream scorecard graphic — 18-hole grid, HCC arched on top, BAD DECISIONS · GOOD TIMES along the bottom. Garment-dyed heavyweight black tee (Comfort Colors 1717).",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-golf-scorecard.jpg",
    cartoonImage: "/images/products/tee-golf-scorecard.webp",
    printfulProductId: 586,
    printfulColor: "Black",
  },
  {
    id: "prod_035",
    name: "Cart Path Bandits Tee",
    slug: "tee-golf-cart-bandits",
    price: 48,
    category: "tees",
    isNew: true,
    isSoldOut: false,
    description:
      "Skull-cowboy mascot driving a golf cart, kicking up dust on the cart path. HOODLUMS COUNTRY CLUB top arc, BAD DECISIONS · GOOD TIMES bottom. Garment-dyed heavyweight black tee (Comfort Colors 1717).",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"],
    image: "/images/products/printful/tee-golf-cart-bandits.jpg",
    cartoonImage: "/images/products/tee-golf-cart-bandits.webp",
    printfulProductId: 586,
    printfulColor: "Black",
  },

  // ---------- HATS (NOT Printful — leather/embroidered, sourced separately) ----------
  {
    id: "prod_012",
    name: "Classic Trucker",
    slug: "hat-classic-trucker",
    price: 34,
    category: "hats",
    isNew: true,
    isSoldOut: false,
    description:
      "Richardson 112 — black twill front, woodland camo mesh back, gold rope-style embroidered logo.",
    sizes: ["One Size"],
    image: "/images/products/hat-classic-trucker.webp",
    cartoonImage: "/images/products/hat-classic-trucker-cartoon.webp",
  },
  {
    id: "prod_013",
    name: "Leather Patch Trucker",
    slug: "hat-leather-patch",
    price: 38,
    category: "hats",
    isNew: false,
    isSoldOut: false,
    description:
      "Richardson 112 all-black with laser-engraved CH genuine leather patch. Handcrafted small-batch feel.",
    sizes: ["One Size"],
    image: "/images/products/hat-leather-patch.webp",
    cartoonImage: "/images/products/hat-leather-patch-cartoon.webp",
  },
  {
    id: "prod_021",
    name: "Mascot Patch Hat",
    slug: "hat-leather-mascot-skull",
    price: 42,
    category: "hats",
    isNew: true,
    isSoldOut: false,
    description:
      "Richardson 112 all-black with a laser-engraved veg-tanned leather patch — HOODLUMS COUNTRY CLUB arched at the top, skull-cowboy mascot centered, EST. 2024 at the bottom.",
    sizes: ["One Size"],
    image: "/images/products/hat-leather-mascot-skull.webp",
    cartoonImage: "/images/products/hat-leather-mascot-skull-cartoon.webp",
  },
  {
    id: "prod_022",
    name: "Crew Crest Patch Hat",
    slug: "hat-leather-crossed-arms",
    price: 42,
    category: "hats",
    isNew: true,
    isSoldOut: false,
    description:
      "Richardson 112 all-black with a laser-engraved veg-tanned leather patch — HOODLUMS COUNTRY CLUB arched at the top, crossed shotgun + fishing rod with a cowboy hat at the intersection, EST. 2024 along the bottom.",
    sizes: ["One Size"],
    image: "/images/products/hat-leather-crossed-arms.webp",
    cartoonImage: "/images/products/hat-leather-crossed-arms-cartoon.webp",
  },
  {
    id: "prod_023",
    name: "Sunset Highway Patch Hat",
    slug: "hat-leather-sunset-highway",
    price: 42,
    category: "hats",
    isNew: true,
    isSoldOut: false,
    description:
      "Richardson 112 all-black with a laser-engraved leather patch — HOODLUMS COUNTRY CLUB arched at the top, a sunset-and-dirt-road silhouette with a lifted truck kicking dust, LIVE EACH DAY along the bottom.",
    sizes: ["One Size"],
    image: "/images/products/hat-leather-sunset-highway.webp",
    cartoonImage: "/images/products/hat-leather-sunset-highway.webp",
  },
  {
    id: "prod_024",
    name: "Tree of Hoodlums Patch Hat",
    slug: "hat-leather-tree-of-hoodlums",
    price: 44,
    category: "hats",
    isNew: true,
    isSoldOut: false,
    description:
      "Richardson 112 all-black with a laser-engraved leather patch — a stylized tree-of-life with HOODLUMS arched in the upper branches, COUNTRY CLUB arched along the roots, and the skull-cowboy mascot in the trunk.",
    sizes: ["One Size"],
    image: "/images/products/hat-leather-tree-of-hoodlums.webp",
    cartoonImage: "/images/products/hat-leather-tree-of-hoodlums.webp",
  },
  {
    id: "prod_025",
    name: "Bonfire Country Patch Hat",
    slug: "hat-leather-bonfire-country",
    price: 42,
    category: "hats",
    isNew: true,
    isSoldOut: false,
    description:
      "Richardson 112 all-black with a laser-engraved leather patch — HOODLUMS COUNTRY CLUB arched at the top, a country bonfire flanked by pine silhouettes, EST. 2024 along the bottom.",
    sizes: ["One Size"],
    image: "/images/products/hat-leather-bonfire-country.webp",
    cartoonImage: "/images/products/hat-leather-bonfire-country.webp",
  },
  {
    id: "prod_026",
    name: "Compass Heritage Patch Hat",
    slug: "hat-leather-compass-heritage",
    price: 44,
    category: "hats",
    isNew: true,
    isSoldOut: false,
    description:
      "Richardson 112 all-black with a laser-engraved leather patch — an 8-point compass rose with HOODLUMS COUNTRY CLUB wrapping the outer ring and the skull-cowboy mascot at the compass center.",
    sizes: ["One Size"],
    image: "/images/products/hat-leather-compass-heritage.webp",
    cartoonImage: "/images/products/hat-leather-compass-heritage.webp",
  },
  {
    id: "prod_014",
    name: "Hoodlum Dad Hat",
    slug: "hat-dad-hat",
    price: 32,
    category: "hats",
    isNew: false,
    isSoldOut: false,
    description:
      "Richardson 320 olive drab unstructured. Minimal gold skull-cowboy embroidery, brass-buckle strap back.",
    sizes: ["One Size"],
    image: "/images/products/hat-dad-hat.webp",
    cartoonImage: "/images/products/hat-dad-hat-cartoon.webp",
  },
  {
    id: "prod_015",
    name: "Gold Brim Snapback",
    slug: "hat-snapback",
    price: 36,
    category: "hats",
    isNew: false,
    isSoldOut: false,
    description:
      "Richardson 511 flat brim. Black panels with metallic gold brim and 3D puff CH monogram.",
    sizes: ["One Size"],
    image: "/images/products/hat-snapback.webp",
    cartoonImage: "/images/products/hat-snapback-cartoon.webp",
  },

  // ---------- CREWNECKS (grouped under hoodies) ----------
  {
    id: "prod_016",
    name: "Vintage Crewneck",
    slug: "crewneck-vintage",
    price: 68,
    category: "hoodies",
    isNew: true,
    isSoldOut: false,
    description:
      "Garment-dyed Pepper (washed gray) crewneck (Comfort Colors 1466). Retro collegiate HOODLUMS COUNTRY CLUB in cream with gold outline.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/printful/crewneck-vintage.jpg",
    cartoonImage: "/images/products/crewneck-vintage-cartoon.webp",
    printfulProductId: 971,
    printfulColor: "Pepper",
    printfulVariantIds: {
      "2XL": 5324420174,
      "3XL": 5324420175,
      "L": 5324420176,
      "M": 5324420177,
      "S": 5324420178,
      "XL": 5324420179,
    },
  },
  {
    id: "prod_017",
    name: "Chain-Stitch Crewneck",
    slug: "crewneck-embroidered",
    price: 75,
    category: "hoodies",
    isNew: false,
    isSoldOut: false,
    description:
      "Black crewneck (Champion S149). Minimal gold chain-stitch Hoodlums Country Club script on the left chest.",
    sizes: ["S", "M", "L", "XL", "2XL"],
    image: "/images/products/crewneck-embroidered.webp",
    cartoonImage: "/images/products/crewneck-embroidered-cartoon.webp",
    printfulProductId: 318,
    printfulColor: "Black",
  },
  {
    id: "prod_018",
    name: "Compass Crewneck",
    slug: "crewneck-graphic",
    price: 70,
    category: "hoodies",
    isNew: false,
    isSoldOut: false,
    description:
      "Garment-dyed Pepper crewneck (Comfort Colors 1466). Golden compass-rose graphic with dirt-road horizon at the center.",
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    image: "/images/products/crewneck-graphic.webp",
    cartoonImage: "/images/products/crewneck-graphic-cartoon.webp",
    printfulProductId: 971,
    printfulColor: "Pepper",
  },

  // ---------- ACCESSORIES ----------
  {
    id: "prod_019",
    name: "The Collection Sticker Pack",
    slug: "collection-flatlay",
    price: 12,
    category: "accessories",
    isNew: true,
    isSoldOut: false,
    description:
      "Six die-cut vinyl stickers featuring the full Hoodlums Country Club collection. Waterproof and weatherproof.",
    sizes: [],
    image: "/images/products/collection-flatlay.webp",
    cartoonImage: "/images/products/collection-flatlay-cartoon.webp",
  },
  {
    id: "prod_020",
    name: "Mood Board Pin Set",
    slug: "lifestyle-moodboard",
    price: 18,
    category: "accessories",
    isNew: true,
    isSoldOut: false,
    description:
      "Four enamel pins capturing the brand mood: hoodie, hat, lantern stack, bonfire cooler. Gold edges throughout.",
    sizes: [],
    image: "/images/products/lifestyle-moodboard.webp",
    cartoonImage: "/images/products/lifestyle-moodboard-cartoon.webp",
  },
];
